#!/usr/bin/env node
var transform= require("stream").Transform

function a(opts){
	if(!(this instanceof a)) return new o(slot)
	transform.call(this, opts)

	this.push("[")
	return this
}
a.prototype._flush= function(cb){
	this.push("]")
	cb()
}

require("./_transform")(a,module,function(opts){
	return this.usage("Usage: $0")
})
