#!/usr/bin/env node
var transform= require("stream").Transform

function o(opts){
	if(!(this instanceof o)) return new o(slot)
	transform.call(this, opts)

	this.push("{"+(opts._[0]||"o")+":")
	return this
}
function _flush(cb){
	this.push("}")
	cb()
}

module.exports= o;
o.prototype._flush= _flush;

require("./_transform")(module,function(val){
	return this.usage("Usage: $0 (slot)")
});
