#!/usr/bin/env node
var transform= require("stream").Transform

function o(opts){
	if(!(this instanceof o)) return new o(slot)
	transform.call(this, opts)

	this.push("{"+(opts._[0]||"o")+":")
	return this
}
o.prototype._flush= function(cb){
	this.push("}")
	cb()
}

require("./_transform")(o,module,function(val){
	return this.usage("Usage: $0 (slot)")
})
